[project]
requires-python = ">=3.10"
dependencies = [
    "pytest-playwright",
    "requests",
    "pytest",
    "playwright",
    "dynaconf",
    "pre-commit"
]

[tool.dynaconf]
settings_files = ["conf/settings.yaml"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
